routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostImageController;
use App\Http\Controllers\UserImageController;
use App\Http\Controllers\Auth\RegisteredUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::permanentRedirect('/', '/login');

Route::resource('/user', RegisteredUserController::class)
    ->except(['show', 'index', 'create', 'update'])
    ->middleware(['verified']);

Route::put('/user/{user:username}', [RegisteredUserController::class, 'update'])
    ->middleware(['verified']);

Route::get('/user/{user:username}', [RegisteredUserController::class, 'show'])
    ->middleware(['verified']);

//Search
Route::get('/search', [RegisteredUserController::class, 'index'])
    ->middleware(['auth'])
    ->name('search');

//Following
Route::get('/user/{user:username}/following', [RegisteredUserController::class, 'listFollowing'])
    ->middleware(['verified']);

//Followers
Route::get('/user/{user:username}/followers', [RegisteredUserController::class, 'listFollowers'])
    ->middleware(['verified']);

//Follow/ Unfollow
Route::post('/user/{user:username}/follow', [FollowController::class, 'store'])
    ->middleware(['verified']);

Route::delete('/user/{user:username}/unfollow', [FollowController::class, 'destroy'])
    ->middleware(['verified']);

//Post CRUD
Route::resource('/post', PostController::class)
    ->except(['index'])
    ->middleware(['verified']);

//Feed
Route::get('/feed', [PostController::class, 'index'])
    ->middleware(['verified'])
    ->name('feed');

//Share
Route::get('/post/{post}/share', [PostController::class, 'share'])
->middleware(['verified']);

//Comment CRUD
Route::resource('/comment', CommentController::class)
    ->except(['create', 'index', 'show'])
    ->middleware(['verified']);

//Comment List
Route::get('/user/{user:username}/comments', [CommentController::class, 'index'])
    ->middleware(['verified']);

//Like
Route::post('/post/{post}/like', [LikeController::class, 'store'])
    ->middleware(['verified']);

//Like
Route::delete('/post/{post}/unlike', [LikeController::class, 'destroy'])
->middleware(['verified']);

//Appears to be the new counterpart to Auth::routes();
require __DIR__ . '/auth.php';

//Post Image
Route::get('/post/{post}/image', PostImageController::class)
    ->middleware(['verified']);

//User Image
Route::get('/user/{user:username}/image', UserImageController::class)
    ->middleware(['verified']);

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Post extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'user_id',
        'original_post_id',
        'content',
        'image_path',
        'created_at',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function comments(bool $paginated = false)
    {
        if ($paginated) {
            return $this->hasMany(Comment::class)
                ->orderByDesc("created_at")
                ->paginate(config('constants.page_size'));
        }

        return $this->hasMany(Comment::class);
    }

    public function originalPost()
    {
        return $this->belongsTo(Post::class, 'original_post_id');
    }

    public static function postsFromFollowing(User $user)
    {
        $followIds = $user->follows->pluck('id');

        $posts = Post::whereIn('user_id', $followIds)
            ->orderByDesc("created_at")
            ->paginate(config('constants.page_size'));

        return $posts;
    }

    public function createdAtRelative()
    {
        return Carbon::parse($this->created_at)->diffForHumans();
    }

    public function updatedAtRelative()
    {
        return Carbon::parse($this->updated_at)->diffForHumans();
    }

    // public function likeCount()
    // {
    //     return Like::where('post_id', $this->id)->count();
    // }

    public function likeCount()
    {
        $count = $this->belongsToMany(Post::class, 'likes', 'post_id', 'user_id')->count();
        if ($count == 0) {
            return;
        }

        if ($count == 1) {
            return "1 Like";
        }

        return $count . ' Likes';
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::postsFromFollowing(Auth::user());

        return view('feed', [
            'posts' => $posts,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'content' => ['required', 'string', 'max:140'],
            //Not filtering by specific mimetypes for now
            'image' => ['image', 'max:5000', 'nullable'],
            'original_post_id' => ['integer', 'nullable'],
        ]);

        if (Arr::has($validated, 'image')) {
            $filename = $request->file('image')->store('post_images');
            $filename = str_replace('post_images/', '', $filename);
            $validated['image_path'] = $filename;
        }

        $validated['user_id'] = Auth::id();
        Post::create($validated);

        return redirect('/feed')
            ->with('status', 'Post successfully created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    // public function show(Post $post)
    public function show(Post $post)
    {
        $comments = $post->comments(true);

        return view('post.show', [
            'post' => $post,
            'comments' => $comments
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        if (! Gate::allows('modify-post', $post)) {
            abort(403);
        }

        return view('post.edit', [
            'post' => $post
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        if (! Gate::allows('modify-post', $post)) {
            abort(403);
        }

        $validated = $request->validate([
            'content' => ['required', 'string', 'max:140'],
        ]);

        $post->update($validated);

        return redirect('/post/' . $post->id)
            ->with('status', 'Post successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        if (! Gate::allows('modify-post', $post)) {
            abort(403);
        }

        foreach ($post->comments as $comment) {
            $comment->delete();
        }

        $post->delete();

        return redirect('/feed')
            ->with('status', 'Post successfully deleted!');
    }

    public function share(Post $post)
    {
        return view('post.share', [
            'post' => $post
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/post/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create New Post') }}
        </h2>
    </x-slot>
    
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                     @include('layouts.new-post')
                </div>
            </div>
        </div>
    </div>
    
</x-app-layout>

resources/views/post/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Edit Post') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <!-- Validation Errors -->
                    <x-validation-errors class="mb-4" :errors="$errors" />

                    <form action="/post/{{ $post->id }}" method="POST">
                        @csrf
                        @method('PUT')
                        
                        <div class="mt-4">
                            <x-label for="content" :value="__('Post')" />
            
                            <x-input id="content" class="block mt-1 w-full"  name="content" :value="$post->content"  />
                        </div>
                        
                        <x-button>Submit</x-button>
                    </form>
                </div> 

                <div class="p-6 bg-white border-b border-gray-200">
                    @include('layouts.post')
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/post/share.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Share Post') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <!-- Validation Errors -->
                    <x-validation-errors class="mb-4" :errors="$errors" />

                    <form method="POST" action="{{ route('post.store') }}" >
                        @csrf

                        <div class="mt-4">
                            <x-label for="content" :value="__('Add Comment to Shared Post')" />
                            <x-input id="content" class="block mt-1 w-full"  name="content"  />
                        </div>

                        @isset($post->original_post_id)
                            <x-input id="original_post_id" type="hidden" name="original_post_id" :value="$post->original_post_id"/>
                        @else   
                            <x-input id="original_post_id" type="hidden" name="original_post_id" :value="$post->id"/>
                        @endisset
                        
                        <x-button>Create Post</x-button>
                    </form>
                </div> 

                <div class="p-6 bg-white border-b border-gray-200">
                    @include('layouts.post')
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/post/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Post') }}
        </h2>
    </x-slot>
    
    @include('layouts.alert')

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg p-6 border-b border-gray-200">
                @include('layouts.post')
                @include('layouts.post-buttons')
            </div>
        </div>
    </div>
    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        @if (Auth::user()->follows->contains($post->user) 
            || Auth::id() == $post->user->id)
            Comments:
            <div class="p-6 bg-white border-b border-gray-200">
                <!-- Validation Errors -->
                <x-validation-errors class="mb-4" :errors="$errors" />
                <form method="POST" action="{{ route('comment.store') }}" enctype="multipart/form-data">
                    @csrf
        
                    <!-- Comment Field -->
                    <div class="mt-4">
                        <x-label for="content" :value="__('Write a Comment')" />
                        <x-input id="post_id" type="hidden" name="post_id" :value="$post->id"/>
                        <x-input id="content" class="block mt-1 w-full"  name="content" :value="old('content')"  />
                    </div>
                    
                    <div class="flex items-center justify-end mt-4">
                        {{-- <x-button class="ml-4">
                            {{ __('Submit Comment') }}
                        </x-button> --}}
                        <x-button>Submit Comment</x-button>
                    </div>
                </form>
            </div>
            
            @forelse ($comments as $comment)
                <div class="p-6 bg-white border-b border-gray-200">
                    @include('layouts.comment')
                    @include('layouts.comment-buttons')
                </div>
            @empty
                No comments available.
            @endforelse
            {{ $comments->links() }}
        @else
            <div class="p-6 bg-white border-b border-gray-200">
                Comments cannot be viewed. Follow post author first.
            </div>
        @endif
    </div>

</x-app-layout>