routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\FollowController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\PostImageController;
use App\Http\Controllers\UserImageController;
use App\Http\Controllers\Auth\RegisteredUserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::permanentRedirect('/', '/login');

Route::resource('/user', RegisteredUserController::class)
    ->except(['show', 'index', 'create', 'update'])
    ->middleware(['verified']);

Route::put('/user/{user:username}', [RegisteredUserController::class, 'update'])
    ->middleware(['verified']);

Route::get('/user/{user:username}', [RegisteredUserController::class, 'show'])
    ->middleware(['verified']);

//Search
Route::get('/search', [RegisteredUserController::class, 'index'])
    ->middleware(['auth'])
    ->name('search');

//Following
Route::get('/user/{user:username}/following', [RegisteredUserController::class, 'listFollowing'])
    ->middleware(['verified']);

//Followers
Route::get('/user/{user:username}/followers', [RegisteredUserController::class, 'listFollowers'])
    ->middleware(['verified']);

//Follow/ Unfollow
Route::post('/user/{user:username}/follow', [FollowController::class, 'store'])
    ->middleware(['verified']);

Route::delete('/user/{user:username}/unfollow', [FollowController::class, 'destroy'])
    ->middleware(['verified']);

//Post CRUD
Route::resource('/post', PostController::class)
    ->except(['index'])
    ->middleware(['verified']);

//Feed
Route::get('/feed', [PostController::class, 'index'])
    ->middleware(['verified'])
    ->name('feed');

//Share
Route::get('/post/{post}/share', [PostController::class, 'share'])
->middleware(['verified']);

//Comment CRUD
Route::resource('/comment', CommentController::class)
    ->except(['create', 'index', 'show'])
    ->middleware(['verified']);

//Comment List
Route::get('/user/{user:username}/comments', [CommentController::class, 'index'])
    ->middleware(['verified']);

//Like
Route::post('/post/{post}/like', [LikeController::class, 'store'])
    ->middleware(['verified']);

//Like
Route::delete('/post/{post}/unlike', [LikeController::class, 'destroy'])
->middleware(['verified']);

//Appears to be the new counterpart to Auth::routes();
require __DIR__ . '/auth.php';

//Post Image
Route::get('/post/{post}/image', PostImageController::class)
    ->middleware(['verified']);

//User Image
Route::get('/user/{user:username}/image', UserImageController::class)
    ->middleware(['verified']);

resources/views/layouts/alert.blade.php
@if (session('status') != null)
    <script>
        alert('{{ session('status') }}');
    </script>   
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>
            
            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/comment-buttons.blade.php
@if (Auth::id() == $comment->user_id)
    <div class="flex flex-row">
        <x-button type="button" onclick="document.location='/comment/{{ $comment->id }}/edit'">
            Edit Comment
        </x-button>

        <form action="/comment/{{ $comment->id }}" method="POST" 
            onsubmit="return confirm('Delete this comment?');">
            @csrf
            @method('delete')

            <x-button>Delete Comment</x-button>
        </form>
    </div>
@endif

resources/views/layouts/comment.blade.php
<div class="flex flex-row">
    <div>
        <a href="/user/{{ $comment->user->username }}">
            <img src="/user/{{ $comment->user->username }}/image" width="50">
        </a>
    </div>

    <div class="flex-grow pl-6">
        <div>
            <a href="/user/{{ $comment->user->username }}">
                {{ $comment->user->fullName() }}
            </a>
            
            <x-label :value="'· ' . $comment->user->username" />
            ·
            <x-label :value="$comment->createdAtRelative()" />

            @if ($comment->created_at != $comment->updated_at)
                <x-label :value="'(Edited ' . $comment->updatedAtRelative() . ')'" />
            @endif
        </div>

        <div class="block">
            {{ $comment->content }}
        </div>
    </div>
</div>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('feed') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    {{-- <x-nav-link :href="route('feed')" 
                    :active="request()->routeIs('feed')">
                        {{ __('Feed') }}
                    </x-nav-link> --}}
                    
                    <x-nav-link :href="route('post.create')"
                    :active="request()->routeIs('post.create')">
                        {{ __('New Post') }}
                    </x-nav-link>

                    <x-nav-link :href="'/user/' . Auth::user()->username" 
                    :active="request()->is('user/' . Auth::user()->username)">
                        {{ __('Profile') }}
                    </x-nav-link>

                    <x-nav-link :href="'/user/' . Auth::user()->username . '/following'" 
                        :active="request()->is('user/' . Auth::user()->username . '/following')">
                            {{ __('Following') }}
                    </x-nav-link>

                    <x-nav-link :href="'/user/' . Auth::user()->username . '/followers'" 
                        :active="request()->is('user/' . Auth::user()->username . '/followers')">
                            {{ __('Followers') }}
                    </x-nav-link>

                    <x-nav-link :href="'/user/' . Auth::user()->username . '/comments'" 
                        :active="request()->is('user/' . Auth::user()->username . '/comments')">
                            {{ __('Comments') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->fullName() }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->

                        <x-dropdown-link :href="'/user/' . Auth::user()->username">
                                {{ __('Profile') }}
                        </x-dropdown-link>
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf
                            

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu --> 
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('feed')" :active="request()->routeIs('feed')">
                {{ __('Feed') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>

resources/views/layouts/new-post.blade.php
@error('content')
    <div class="font-medium text-red-600">
        {{ __('Whoops! Something went wrong.') }}
    </div>

    <ul class="mt-3 list-disc list-inside text-sm text-red-600">
        <li>{{ $message }}</li>
    </ul>
@enderror

<form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
    @csrf

    <!-- Post Content -->
    <div class="mt-4">
        <x-label for="content" :value="__('Post')" />

        <x-input id="content" class="block mt-1 w-full"  name="content" :value="old('content')"  />
    </div>

    <!-- Post Attachment -->
    <div class="mt-4">
        <x-label for="image" :value="__('Attach an image (Optional)')" />

        <x-label :value="__('Supported formats: jpg, jpeg, png, bmp, gif, svg, webp')"
        class="block"/>    

        <x-label :value="__('Maximum size: 5 MB')" class="block"/>   

        <x-input id="image" class="block mt-1 w-full"
                        type="file"
                        name="image"
                        onchange="previewFile()"/>
    </div>

    <div>
        <img id="preview" width="100">
    </div>
    
    <div class="flex items-center justify-end mt-4">
        <x-button>Submit Post</x-button>
    </div>
</form>

<script>
    // template taken from readAsDataURL example
    function previewFile() {
        const preview = document.getElementById('preview');
        const file = document.querySelector('input[type=file]').files[0];
        const reader = new FileReader();

        reader.addEventListener("load", function () {
            preview.src = reader.result;
        }, false);

        if (file) {
            reader.readAsDataURL(file);
        }
    }
</script>

resources/views/layouts/post-buttons.blade.php
<div class="flex flex-row">
    @if (Auth::id() == $post->user_id)
        <div>
            <x-button type="button" onclick="document.location='/post/{{ $post->id }}/edit'">
                Edit Post
            </x-button>
        </div>

        <div>
            <form action="/post/{{ $post->id }}" method="POST"
                onsubmit="return confirm('Delete this post?');">
                @csrf
                @method('delete')

                <x-button>Delete Post</x-button>
            </form>
        </div>
    @endif

    <div>
        <x-button type="button" onclick="document.location='/post/{{ $post->id }}/share'">
            Share
        </x-button>
    
    </div>

    <div> 
        @if (Auth::user()->likes->contains($post) )
            <form method="POST" action="/post/{{ $post->id }}/unlike" >
                @csrf
                @method('delete')
                
                <x-button>Liked</x-button>
            </form>
            
        @else
            <form method="POST" action="/post/{{ $post->id }}/like" >
                @csrf

                <x-button>Like</x-button>
            </form>
        
        @endif
    </div>

    @if(!request()->is('post/' . $post->id))
        <div>
            <x-button type="button" onclick="document.location='/post/{{ $post->id }}'">
                Show Comments
            </x-button>
        
        </div>
    @endif
</div>

resources/views/layouts/post.blade.php
<div class="flex flex-row">
    <div>
        <a href="/user/{{ $post->user->username }}">
            <img src="/user/{{ $post->user->username }}/image" width="50">
        </a>
    </div>
    
    <div class="flex-grow pl-6">
        <div>
            <a href="/user/{{ $post->user->username }}">
                {{ $post->user->fullName() }}
            </a>
            
            <x-label :value="'· ' . $post->user->username" />
            ·
            <x-label :value="$post->createdAtRelative()" />
                
            @if ($post->created_at != $post->updated_at)
                <x-label :value="'(Edited ' . $post->updatedAtRelative() . ')'" />
            @endif
        </div>
        
        @if (Auth::user()->follows->contains($post->user) 
        || Auth::user()->id == $post->user->id)
            <div>
                <a href="/post/{{ $post->id }}">
                    {{ $post->content }}
                </a>
            </div>

            @isset($post->image_path)
                <div>
                    <img 
                        src="/post/{{ $post->id }}/image"
                        width="200"
                    />
                </div>
            @endisset

            {{ $post->likeCount() }}

            @isset($post->original_post_id)
                <div class="p-6 bg-white border border-gray-200">
                    @isset($post->originalPost)
                        @include('layouts.post', $post = $post->originalPost)
                    @else 
                        Content not found.
                    @endisset
                </div>
            @endisset
        @else
            Post cannot be viewed. Follow post author first.
        @endif

        
    </div>
</div>

resources/views/layouts/search.blade.php
@error('term')
    <div class="font-medium text-red-600">
        {{ __('Whoops! Something went wrong.') }}
    </div>

    <ul class="mt-3 list-disc list-inside text-sm text-red-600">
        <li>{{ $message }}</li>
    </ul>
@enderror

<form method="GET" action="{{ route('search') }}" >
    <!-- Search Bar -->
    <div class="mt-4">
        <x-label for="term" :value="__('Search')" />

        <x-input id="term" class="block mt-1 w-full"  name="term" />
    </div>

    <div class="flex items-center justify-end mt-4">
        <x-button>Search</x-button>
    </div>
</form>

resources/views/layouts/user-buttons.blade.php
@if (Auth::user()->follows->contains($user) )
    <form method="POST" action="/user/{{ $user->username }}/unfollow" >
        @csrf
        @method('delete')

        <x-button>Unfollow</x-button>
    </form>
@else
    <form method="POST" action="/user/{{ $user->username }}/follow" >
        @csrf

        <x-button>Follow</x-button>
    </form>
@endif

resources/views/layouts/user.blade.php
<div>
    <a href="/user/{{ $user->username }}">
        <img src="/user/{{ $user->username }}/image" width="50">
    </a>
</div>

<div>
    Username: {{ $user->username }} <br>
    Name: {{ $user->fullName() }} 
</div>